version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      # ignore backstage packages, we need to update them with backstage-cli in accordance
      # with the backstage version supported by RHDH. You can see the version here
      # https://github.com/redhat-developer/rhdh/blob/main/backstage.json selecting the correct
      # branch or tag
      - dependency-name: "@backstage/*"
    groups:
      # Group testing packages together
      testing:
        patterns:
          - "@jest/*"
          - "@playwright/*"
          - "@types/jest"
          - "jest"
      # Group TypeScript packages together
      typescript:
        patterns:
          - "typescript"
          - "@types/*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-actions-dependencies:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5
